### ISSUE TITLE
GfyCat currently doesn't support SSL through API. 

### ISSUE THREAD

**Issue by a5mith** [a5mith/nodebb-plugin-gfycat#1]
So it throws an error on community.nodebb.org, (probably doesn't load at all in Chrome), problem reported here: http://www.reddit.com/r/gfycat/comments/2dyj4o/bug_gfycat_json_returns_http_not_https_urls/

Shouldn't require any changes to the plugin, as I believe they're just making everything https...

**Comment by zetas** [comment]
This appears to still be an issue. Is there any way you can do a string replace or something and swap http to a scheme-less url? //?
